@startmindmap
* Безопасность данных
  * Публичные данные\n-- Риски --\n* утечка данных(**незначительный**): не страшно, так как это публичные данные\n* потеря данных(**значительный**): может временно повлиять на работу витрины\n* искажение данных(**значительный**): ошибочные цены/описания будут мешать клиентам при использовании сервиса\n* некачественные данные(**значительный**): ошибки отпугивают клиентов, сервис теряет доверие клиентов, будет сложно восстановить репутацию\n* обесценивание данных(**незначительный**): например, когда конкуренты будут использовать описания/фото из объявлений
    * Витрина продаж
    * Витрина услуг
  * Внутренние данные\n-- Риски --\n* утечка данных(**значительный**): может раскрыть конкурентам логику работу сервиса, какие-то внутренние технические особенности системы\n* потеря данных(**значительный**): усложнит поддержку и разработку сервиса в будущем\n* искажение данных(**значительный**): аналитика и отчёты будут неверными, неактуальная документация\n* некачественные данные(**значительный**): ошибки в аналитике, документация вводящая в заблуждение\n* обесценивание данных(**незначительный**): быстро теряют актуальность без поддержки
    * Технические логи приложений и сервисов
    * Внутренняя документация
  * Конфиденциальные данные\n-- Риски --\n* утечка данных(**критический**): нарушение закона(например, ФЗ-152), репутационные и юридические риски\n* потеря данных(**критический**): потеря истории сделок, ЖКХ — приводит к недоверию и претензиям клиентов\n* искажение данных(**критический**): неверные коммуникации, ошибки в квитанциях за ЖКХ и тд\n* некачественные данные(**значительный**): проблемы с обслуживанием клиентов, повышенное кол-во обращений\n* обесценивание данных(**значительный**): при устаревании/недостоверности теряет актуальность для поддержки и CRM
    * Данные клиентов и собственников
    * Данные о сделках
    * История онлайн-просмотров
    * История оплат жкх
    * Показания счётчиков
    * Финансовые данные
  * Секретные данные\n-- Риски --\n* утечка данных(**критический**): прямой путь к взлому, доступ к внутренним системам, выгрузка информации\n* потеря данных(**критический**): потеря ключей, отказ в доступе, невозможность восстановить\n* искажение данных(**критический**): заменённые ключи — потенциальная компрометация\n* некачественные данные(**критический**): ошибки в настройках безопасности, могут приводить к плохим последствиям\n* обесценивание данных(**значительный**): если ключи не обновляются, то становятся уязвимыми со временем
    * Доступы к БД
    * Доступы к логам
@endmindmap
